In [55]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\priya\Downloads\students_data_2000_rows.csv")
print(df.head(10))

   Student_ID        Name  Age  Gender Department        City  Marks  \
0        1001   Student_1   19    Male        ECE  Chandigarh     63
1        1002   Student_2   19    Male         CE    Amritsar     39
2        1003   Student_3   19    Male         IT      Jaipur     38
3        1004   Student_4   21  Female         IT    Amritsar     70
4        1005   Student_5   20  Female        ECE    Ludhiana     54
5        1006   Student_6   23    Male        CSE    Amritsar     47
6        1007   Student_7   23  Female        CSE    Amritsar     50
7        1008   Student_8   19  Female         CE    Ludhiana     59
8        1009   Student_9   18    Male        ECE       Delhi     64
9        1010  Student_10   24  Female         ME    Ludhiana     55

   Attendance
0          68
1          61
2          95
3          60
4          73
5          82
6          84
7          64
8          66
9          83

In [3]:
df.tail(10)
print(df.tail(10))

      Student_ID          Name  Age  Gender Department        City  Marks  \
1990        2991  Student_1991   19    Male         ME       Delhi     83
1991        2992  Student_1992   18    Male         CE       Delhi     56
1992        2993  Student_1993   25    Male        CSE    Amritsar     98
1993        2994  Student_1994   25    Male         CE    Amritsar     86
1994        2995  Student_1995   22    Male         ME    Ludhiana     69
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
1990          68
1991          72
1992          70
1993          60
1994          93
1995          78
1996          90
1997          93
1998          69
1999          72

In [4]:
df.shape

(2000, 8)

In [5]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'Marks',
       'Attendance'],
      dtype='str')

In [6]:
df.dtypes

Student_ID    int64
Name            str
Age           int64
Gender          str
Department      str
City            str
Marks         int64
Attendance    int64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  2000 non-null   int64
 1   Name        2000 non-null   str
 2   Age         2000 non-null   int64
 3   Gender      2000 non-null   str
 4   Department  2000 non-null   str
 5   City        2000 non-null   str
 6   Marks       2000 non-null   int64
 7   Attendance  2000 non-null   int64
dtypes: int64(4), str(4)
memory usage: 125.1 KB

In [8]:
df.describe

<bound method NDFrame.describe of       Student_ID          Name  Age  Gender Department        City  Marks  \
0           1001     Student_1   19    Male        ECE  Chandigarh     63
1           1002     Student_2   19    Male         CE    Amritsar     39
2           1003     Student_3   19    Male         IT      Jaipur     38
3           1004     Student_4   21  Female         IT    Amritsar     70
4           1005     Student_5   20  Female        ECE    Ludhiana     54
...          ...           ...  ...     ...        ...         ...    ...
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
0             68
1             61
2             95
3             60
4             73
...          ...
1995          78
1996          90
1997          93
1998          69
1999          72

[2000 rows x 8 columns]>

In [9]:
df.sample

<bound method NDFrame.sample of       Student_ID          Name  Age  Gender Department        City  Marks  \
0           1001     Student_1   19    Male        ECE  Chandigarh     63
1           1002     Student_2   19    Male         CE    Amritsar     39
2           1003     Student_3   19    Male         IT      Jaipur     38
3           1004     Student_4   21  Female         IT    Amritsar     70
4           1005     Student_5   20  Female        ECE    Ludhiana     54
...          ...           ...  ...     ...        ...         ...    ...
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
0             68
1             61
2             95
3             60
4             73
...          ...
1995          78
1996          90
1997          93
1998          69
1999          72

[2000 rows x 8 columns]>

In [10]:
df['Marks'].mean()

np.float64(67.355)

In [11]:
df[['Name', 'Marks']].head(10)

         Name  Marks
0   Student_1     63
1   Student_2     39
2   Student_3     38
3   Student_4     70
4   Student_5     54
5   Student_6     47
6   Student_7     50
7   Student_8     59
8   Student_9     64
9  Student_10     55

In [12]:
df[df['Marks'] > 80]

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
15,1016,Student_16,21,Female,CE,Amritsar,86,83
19,1020,Student_20,22,Female,CSE,Ludhiana,90,70
23,1024,Student_24,23,Female,CSE,Delhi,81,79
26,1027,Student_27,20,Female,CE,Jaipur,89,73
27,1028,Student_28,21,Female,ME,Ludhiana,91,93
...,...,...,...,...,...,...,...,...
1988,2989,Student_1989,24,Male,ECE,Chandigarh,97,94
1989,2990,Student_1990,25,Female,IT,Ludhiana,94,90
1990,2991,Student_1991,19,Male,ME,Delhi,83,68
1992,2993,Student_1993,25,Male,CSE,Amritsar,98,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86,60

In [13]:
df[df['Marks'] > 80].head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
15,1016,Student_16,21,Female,CE,Amritsar,86,83
19,1020,Student_20,22,Female,CSE,Ludhiana,90,70
23,1024,Student_24,23,Female,CSE,Delhi,81,79
26,1027,Student_27,20,Female,CE,Jaipur,89,73
27,1028,Student_28,21,Female,ME,Ludhiana,91,93
33,1034,Student_34,19,Female,ECE,Amritsar,87,89
35,1036,Student_36,21,Male,IT,Jaipur,92,68
38,1039,Student_39,21,Male,ME,Amritsar,96,73
40,1041,Student_41,22,Female,ECE,Amritsar,97,69
42,1043,Student_43,18,Male,CE,Amritsar,99,93

In [14]:
df[df['Marks'] > 80].tail(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1974,2975,Student_1975,21,Male,ECE,Delhi,83,85
1979,2980,Student_1980,22,Female,ME,Ludhiana,89,65
1980,2981,Student_1981,21,Female,CE,Ludhiana,96,78
1981,2982,Student_1982,21,Female,CSE,Amritsar,85,83
1985,2986,Student_1986,25,Male,CSE,Chandigarh,86,99
1988,2989,Student_1989,24,Male,ECE,Chandigarh,97,94
1989,2990,Student_1990,25,Female,IT,Ludhiana,94,90
1990,2991,Student_1991,19,Male,ME,Delhi,83,68
1992,2993,Student_1993,25,Male,CSE,Amritsar,98,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86,60

In [15]:
df[df['Marks'] > 80].sample(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
19,1020,Student_20,22,Female,CSE,Ludhiana,90,70
358,1359,Student_359,18,Female,ECE,Delhi,85,76
1957,2958,Student_1958,21,Female,ME,Amritsar,85,98
35,1036,Student_36,21,Male,IT,Jaipur,92,68
1304,2305,Student_1305,24,Female,CE,Amritsar,89,88
124,1125,Student_125,22,Male,IT,Delhi,88,98
745,1746,Student_746,19,Female,CE,Jaipur,87,76
1429,2430,Student_1430,18,Male,ME,Delhi,86,98
654,1655,Student_655,25,Male,CSE,Amritsar,87,62
1504,2505,Student_1505,22,Male,ECE,Amritsar,95,92

In [16]:
df.sort_values(by='Marks', ascending=False).head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
974,1975,Student_975,23,Male,CE,Delhi,100,85
854,1855,Student_855,21,Female,CSE,Ludhiana,100,95
1935,2936,Student_1936,24,Female,ME,Chandigarh,100,97
1942,2943,Student_1943,22,Male,CSE,Chandigarh,100,70
304,1305,Student_305,23,Female,IT,Ludhiana,100,95
308,1309,Student_309,23,Male,IT,Amritsar,100,89
1746,2747,Student_1747,22,Female,ME,Amritsar,100,85
636,1637,Student_637,19,Female,IT,Delhi,100,64
1337,2338,Student_1338,22,Female,ECE,Chandigarh,100,78
1450,2451,Student_1451,20,Male,CSE,Amritsar,100,66

In [17]:
df.sort_values(by='Marks', ascending=True).head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
22,1023,Student_23,23,Male,CE,Jaipur,35,98
1282,2283,Student_1283,19,Male,ME,Amritsar,35,75
1622,2623,Student_1623,21,Male,CE,Delhi,35,82
1021,2022,Student_1022,24,Male,CE,Chandigarh,35,84
1654,2655,Student_1655,21,Male,IT,Ludhiana,35,73
337,1338,Student_338,23,Female,CSE,Chandigarh,35,95
393,1394,Student_394,18,Female,ME,Delhi,35,94
946,1947,Student_947,25,Female,CE,Delhi,35,79
1814,2815,Student_1815,19,Male,ME,Ludhiana,35,87
753,1754,Student_754,23,Male,IT,Amritsar,35,65

In [18]:
df.sort_values(by='Marks', ascending=True).tail(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1554,2555,Student_1555,22,Male,ECE,Jaipur,100,98
449,1450,Student_450,19,Male,ECE,Chandigarh,100,84
1935,2936,Student_1936,24,Female,ME,Chandigarh,100,97
854,1855,Student_855,21,Female,CSE,Ludhiana,100,95
1600,2601,Student_1601,23,Female,ME,Delhi,100,87
1746,2747,Student_1747,22,Female,ME,Amritsar,100,85
1570,2571,Student_1571,24,Male,ME,Amritsar,100,94
1942,2943,Student_1943,22,Male,CSE,Chandigarh,100,70
270,1271,Student_271,21,Male,ECE,Ludhiana,100,85
308,1309,Student_309,23,Male,IT,Amritsar,100,89

In [19]:
df.rename(columns={'marks': 'students_marks'})

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [20]:
df.drop('City', axis=1)

      Student_ID          Name  Age  Gender Department  Marks  Attendance
0           1001     Student_1   19    Male        ECE     63          68
1           1002     Student_2   19    Male         CE     39          61
2           1003     Student_3   19    Male         IT     38          95
3           1004     Student_4   21  Female         IT     70          60
4           1005     Student_5   20  Female        ECE     54          73
...          ...           ...  ...     ...        ...    ...         ...
1995        2996  Student_1996   23  Female         CE     53          78
1996        2997  Student_1997   21  Female         CE     67          90
1997        2998  Student_1998   25    Male        ECE     56          93
1998        2999  Student_1999   25    Male        ECE     57          69
1999        3000  Student_2000   25    Male        CSE     59          72

[2000 rows x 7 columns]

In [21]:
df.drop(0)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
5,1006,Student_6,23,Male,CSE,Amritsar,47,82
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [22]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
City          0
Marks         0
Attendance    0
dtype: int64

In [23]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [24]:
df.fillna(0)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [25]:
df.isnull().sum()
df["Marks"].fillna(df["Marks"].mean(),inplace=True)

C:\Users\priya\AppData\Local\Temp\ipykernel_7288\4250698425.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].mean(),inplace=True)

0       63
1       39
2       38
3       70
4       54
        ..
1995    53
1996    67
1997    56
1998    57
1999    59
Name: Marks, Length: 2000, dtype: int64

In [26]:
df.duplicated()
df.drop_duplicates()

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [27]:
df["City"].values

<StringArray>
['Chandigarh',   'Amritsar',     'Jaipur',   'Amritsar',   'Ludhiana',
   'Amritsar',   'Amritsar',   'Ludhiana',      'Delhi',   'Ludhiana',
 ...
      'Delhi',      'Delhi',   'Amritsar',   'Amritsar',   'Ludhiana',
 'Chandigarh',     'Jaipur', 'Chandigarh',   'Amritsar',   'Ludhiana']
Length: 2000, dtype: str

In [28]:
df['City'].unique()

<StringArray>
['Chandigarh', 'Amritsar', 'Jaipur', 'Ludhiana', 'Delhi']
Length: 5, dtype: str

In [29]:
df["City"].nunique()

5

In [30]:
df['Marks'].mean()

np.float64(67.355)

In [31]:
df['Marks'].max()

np.int64(100)

In [32]:
df['Marks'].std()

np.float64(18.928975885240913)

In [33]:
df['Marks'].median()

np.float64(67.0)

In [34]:
df['Marks'].sum()

np.int64(134710)

In [35]:
df['Marks'].var()

np.float64(358.306128064032)

In [36]:
pd.pivot_table(df, values='Marks', index='City', aggfunc='min')

            Marks
City
Amritsar       35
Chandigarh     35
Delhi          35
Jaipur         35
Ludhiana       35

In [37]:
mydf=pd.DataFrame({
    'Product':['Laptop','iPhone','Mac'],
    'Price':[80000, 90000, 120000],
})

In [38]:
df.groupby('Department')['Student_ID'].count()

Department
CE     406
CSE    408
ECE    396
IT     391
ME     399
Name: Student_ID, dtype: int64

In [39]:
df.groupby('City')

In [40]:
df.groupby(["City","Department"])["Marks"].mean()

City        Department
Amritsar    CE            69.407407
            CSE           66.788889
            ECE           69.726190
            IT            64.567901
            ME            70.524390
Chandigarh  CE            68.962500
            CSE           70.447059
            ECE           66.226190
            IT            66.625000
            ME            68.178082
Delhi       CE            64.363636
            CSE           67.413333
            ECE           63.454545
            IT            69.367089
            ME            69.345679
Jaipur      CE            66.604651
            CSE           66.837838
            ECE           63.727273
            IT            64.240964
            ME            66.804878
Ludhiana    CE            67.853659
            CSE           66.928571
            ECE           70.200000
            IT            67.880952
            ME            66.148148
Name: Marks, dtype: float64

In [41]:
df.groupby(["Department", "City"])["Marks"].mean()

Department  City
CE          Amritsar      69.407407
            Chandigarh    68.962500
            Delhi         64.363636
            Jaipur        66.604651
            Ludhiana      67.853659
CSE         Amritsar      66.788889
            Chandigarh    70.447059
            Delhi         67.413333
            Jaipur        66.837838
            Ludhiana      66.928571
ECE         Amritsar      69.726190
            Chandigarh    66.226190
            Delhi         63.454545
            Jaipur        63.727273
            Ludhiana      70.200000
IT          Amritsar      64.567901
            Chandigarh    66.625000
            Delhi         69.367089
            Jaipur        64.240964
            Ludhiana      67.880952
ME          Amritsar      70.524390
            Chandigarh    68.178082
            Delhi         69.345679
            Jaipur        66.804878
            Ludhiana      66.148148
Name: Marks, dtype: float64

In [ ]:
#Q1
students = df[df['Marks']>85].groupby("City")

for city, group in students:
    print(city)
    print(group.head(5))

Amritsar
    Student_ID        Name  Age  Gender Department      City  Marks  \
15        1016  Student_16   21  Female         CE  Amritsar     86
33        1034  Student_34   19  Female        ECE  Amritsar     87
38        1039  Student_39   21    Male         ME  Amritsar     96
40        1041  Student_41   22  Female        ECE  Amritsar     97
42        1043  Student_43   18    Male         CE  Amritsar     99

    Attendance
15          83
33          89
38          73
40          69
42          93
Chandigarh
     Student_ID         Name  Age  Gender Department        City  Marks  \
48         1049   Student_49   19    Male         CE  Chandigarh     99
87         1088   Student_88   25  Female        CSE  Chandigarh     88
111        1112  Student_112   24  Female         CE  Chandigarh     95
154        1155  Student_155   20  Female        CSE  Chandigarh     99
192        1193  Student_193   20  Female        CSE  Chandigarh     88

     Attendance
48           76
87           84
111          91
154          97
192          93
Delhi
     Student_ID         Name  Age  Gender Department   City  Marks  Attendance
61         1062   Student_62   20    Male         ME  Delhi     95          74
124        1125  Student_125   22    Male         IT  Delhi     88          98
140        1141  Student_141   22  Female         CE  Delhi     93          65
141        1142  Student_142   23  Female        ECE  Delhi     86          92
146        1147  Student_147   24    Male         IT  Delhi     94          67
Jaipur
     Student_ID         Name  Age  Gender Department    City  Marks  \
26         1027   Student_27   20  Female         CE  Jaipur     89
35         1036   Student_36   21    Male         IT  Jaipur     92
74         1075   Student_75   25  Female         IT  Jaipur     95
137        1138  Student_138   25  Female         IT  Jaipur     90
214        1215  Student_215   25  Female         ME  Jaipur     91

     Attendance
26           73
35           68
74           70
137         100
214          86
Ludhiana
     Student_ID         Name  Age  Gender Department      City  Marks  \
19         1020   Student_20   22  Female        CSE  Ludhiana     90
27         1028   Student_28   21  Female         ME  Ludhiana     91
66         1067   Student_67   19  Female        ECE  Ludhiana     90
70         1071   Student_71   22  Female         ME  Ludhiana     86
113        1114  Student_114   21  Female         CE  Ludhiana     95

     Attendance
19           70
27           93
66           98
70           78
113          95

In [ ]:
#Q2
CSE_attendance = df[df['Department'] == 'CSE'].sort_values("Attendance")
print(CSE_attendance)

      Student_ID          Name  Age  Gender Department        City  Marks  \
103         1104   Student_104   24  Female        CSE      Jaipur     78
1286        2287  Student_1287   25  Female        CSE    Amritsar     53
975         1976   Student_976   20  Female        CSE    Ludhiana     41
1254        2255  Student_1255   24    Male        CSE    Amritsar     49
1755        2756  Student_1756   20  Female        CSE       Delhi     75
...          ...           ...  ...     ...        ...         ...    ...
512         1513   Student_513   18  Female        CSE  Chandigarh     79
578         1579   Student_579   18  Female        CSE    Amritsar     60
612         1613   Student_613   22  Female        CSE    Amritsar     41
296         1297   Student_297   23  Female        CSE    Ludhiana     60
159         1160   Student_160   22    Male        CSE    Amritsar     47

      Attendance
103           60
1286          60
975           60
1254          60
1755          60
...          ...
512          100
578          100
612          100
296          100
159          100

[408 rows x 8 columns]

In [ ]:
#Q3
marks = df[(df['Age'] > 20) & (df['Age'] < 25)]['Marks']
print(marks)

3       70
5       47
6       50
9       55
10      56
        ..
1987    76
1988    97
1994    69
1995    53
1996    67
Name: Marks, Length: 990, dtype: int64

In [ ]:
#Q5
df["Fees"] = np.random.choice(["Pending","Paid"],size=len(df))
df

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance,Fees
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68,Paid
1,1002,Student_2,19,Male,CE,Amritsar,39,61,Paid
2,1003,Student_3,19,Male,IT,Jaipur,38,95,Paid
3,1004,Student_4,21,Female,IT,Amritsar,70,60,Pending
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73,Paid
...,...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78,Paid
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90,Paid
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93,Pending
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69,Pending
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72,Pending

In [ ]:
#Q6
avg_attendance = df.groupby(['Gender', 'Department'])['Attendance'].mean()
print(avg_attendance)

Gender  Department
Female  CE            79.213270
        CSE           80.826733
        ECE           81.201058
        IT            79.718310
        ME            79.256281
Male    CE            80.087179
        CSE           79.558252
        ECE           81.120773
        IT            79.685393
        ME            81.240000
Name: Attendance, dtype: float64