In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\priya\Downloads\students_data_2000_rows.csv")
print(df.head(10))

   Student_ID        Name  Age  Gender Department        City  Marks  \
0        1001   Student_1   19    Male        ECE  Chandigarh     63
1        1002   Student_2   19    Male         CE    Amritsar     39
2        1003   Student_3   19    Male         IT      Jaipur     38
3        1004   Student_4   21  Female         IT    Amritsar     70
4        1005   Student_5   20  Female        ECE    Ludhiana     54
5        1006   Student_6   23    Male        CSE    Amritsar     47
6        1007   Student_7   23  Female        CSE    Amritsar     50
7        1008   Student_8   19  Female         CE    Ludhiana     59
8        1009   Student_9   18    Male        ECE       Delhi     64
9        1010  Student_10   24  Female         ME    Ludhiana     55

   Attendance
0          68
1          61
2          95
3          60
4          73
5          82
6          84
7          64
8          66
9          83

In [10]:
df.tail(10)
print(df.tail(10))

      Student_ID          Name  Age  Gender Department        City  Marks  \
1990        2991  Student_1991   19    Male         ME       Delhi     83
1991        2992  Student_1992   18    Male         CE       Delhi     56
1992        2993  Student_1993   25    Male        CSE    Amritsar     98
1993        2994  Student_1994   25    Male         CE    Amritsar     86
1994        2995  Student_1995   22    Male         ME    Ludhiana     69
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
1990          68
1991          72
1992          70
1993          60
1994          93
1995          78
1996          90
1997          93
1998          69
1999          72

In [11]:
df.shape

(2000, 8)

In [12]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'Marks',
       'Attendance'],
      dtype='str')

In [13]:
df.dtypes

Student_ID    int64
Name            str
Age           int64
Gender          str
Department      str
City            str
Marks         int64
Attendance    int64
dtype: object

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  2000 non-null   int64
 1   Name        2000 non-null   str
 2   Age         2000 non-null   int64
 3   Gender      2000 non-null   str
 4   Department  2000 non-null   str
 5   City        2000 non-null   str
 6   Marks       2000 non-null   int64
 7   Attendance  2000 non-null   int64
dtypes: int64(4), str(4)
memory usage: 125.1 KB

In [15]:
df.describe

<bound method NDFrame.describe of       Student_ID          Name  Age  Gender Department        City  Marks  \
0           1001     Student_1   19    Male        ECE  Chandigarh     63
1           1002     Student_2   19    Male         CE    Amritsar     39
2           1003     Student_3   19    Male         IT      Jaipur     38
3           1004     Student_4   21  Female         IT    Amritsar     70
4           1005     Student_5   20  Female        ECE    Ludhiana     54
...          ...           ...  ...     ...        ...         ...    ...
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
0             68
1             61
2             95
3             60
4             73
...          ...
1995          78
1996          90
1997          93
1998          69
1999          72

[2000 rows x 8 columns]>

In [16]:
df.sample

<bound method NDFrame.sample of       Student_ID          Name  Age  Gender Department        City  Marks  \
0           1001     Student_1   19    Male        ECE  Chandigarh     63
1           1002     Student_2   19    Male         CE    Amritsar     39
2           1003     Student_3   19    Male         IT      Jaipur     38
3           1004     Student_4   21  Female         IT    Amritsar     70
4           1005     Student_5   20  Female        ECE    Ludhiana     54
...          ...           ...  ...     ...        ...         ...    ...
1995        2996  Student_1996   23  Female         CE  Chandigarh     53
1996        2997  Student_1997   21  Female         CE      Jaipur     67
1997        2998  Student_1998   25    Male        ECE  Chandigarh     56
1998        2999  Student_1999   25    Male        ECE    Amritsar     57
1999        3000  Student_2000   25    Male        CSE    Ludhiana     59

      Attendance
0             68
1             61
2             95
3             60
4             73
...          ...
1995          78
1996          90
1997          93
1998          69
1999          72

[2000 rows x 8 columns]>

In [17]:
df['Marks'].mean()

np.float64(67.355)

In [18]:
df[['Name', 'Marks']].head(10)

         Name  Marks
0   Student_1     63
1   Student_2     39
2   Student_3     38
3   Student_4     70
4   Student_5     54
5   Student_6     47
6   Student_7     50
7   Student_8     59
8   Student_9     64
9  Student_10     55

In [19]:
df[df['Marks'] > 80]

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
15,1016,Student_16,21,Female,CE,Amritsar,86,83
19,1020,Student_20,22,Female,CSE,Ludhiana,90,70
23,1024,Student_24,23,Female,CSE,Delhi,81,79
26,1027,Student_27,20,Female,CE,Jaipur,89,73
27,1028,Student_28,21,Female,ME,Ludhiana,91,93
...,...,...,...,...,...,...,...,...
1988,2989,Student_1989,24,Male,ECE,Chandigarh,97,94
1989,2990,Student_1990,25,Female,IT,Ludhiana,94,90
1990,2991,Student_1991,19,Male,ME,Delhi,83,68
1992,2993,Student_1993,25,Male,CSE,Amritsar,98,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86,60

In [20]:
df[df['Marks'] > 80].head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
15,1016,Student_16,21,Female,CE,Amritsar,86,83
19,1020,Student_20,22,Female,CSE,Ludhiana,90,70
23,1024,Student_24,23,Female,CSE,Delhi,81,79
26,1027,Student_27,20,Female,CE,Jaipur,89,73
27,1028,Student_28,21,Female,ME,Ludhiana,91,93
33,1034,Student_34,19,Female,ECE,Amritsar,87,89
35,1036,Student_36,21,Male,IT,Jaipur,92,68
38,1039,Student_39,21,Male,ME,Amritsar,96,73
40,1041,Student_41,22,Female,ECE,Amritsar,97,69
42,1043,Student_43,18,Male,CE,Amritsar,99,93

In [21]:
df[df['Marks'] > 80].tail(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1974,2975,Student_1975,21,Male,ECE,Delhi,83,85
1979,2980,Student_1980,22,Female,ME,Ludhiana,89,65
1980,2981,Student_1981,21,Female,CE,Ludhiana,96,78
1981,2982,Student_1982,21,Female,CSE,Amritsar,85,83
1985,2986,Student_1986,25,Male,CSE,Chandigarh,86,99
1988,2989,Student_1989,24,Male,ECE,Chandigarh,97,94
1989,2990,Student_1990,25,Female,IT,Ludhiana,94,90
1990,2991,Student_1991,19,Male,ME,Delhi,83,68
1992,2993,Student_1993,25,Male,CSE,Amritsar,98,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86,60

In [27]:
df[df['Marks'] > 80].sample(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
449,1450,Student_450,19,Male,ECE,Chandigarh,100,84
454,1455,Student_455,25,Female,ME,Amritsar,91,91
1751,2752,Student_1752,19,Female,IT,Delhi,100,76
1342,2343,Student_1343,23,Male,IT,Delhi,95,60
959,1960,Student_960,21,Male,CE,Ludhiana,81,85
1782,2783,Student_1783,24,Male,CSE,Ludhiana,89,70
1436,2437,Student_1437,19,Male,CE,Ludhiana,87,88
522,1523,Student_523,23,Male,ME,Ludhiana,94,76
622,1623,Student_623,22,Male,CSE,Amritsar,99,97
445,1446,Student_446,21,Female,CSE,Ludhiana,97,93

In [28]:
df.sort_values(by='Marks', ascending=False).head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
974,1975,Student_975,23,Male,CE,Delhi,100,85
854,1855,Student_855,21,Female,CSE,Ludhiana,100,95
1935,2936,Student_1936,24,Female,ME,Chandigarh,100,97
1942,2943,Student_1943,22,Male,CSE,Chandigarh,100,70
304,1305,Student_305,23,Female,IT,Ludhiana,100,95
308,1309,Student_309,23,Male,IT,Amritsar,100,89
1746,2747,Student_1747,22,Female,ME,Amritsar,100,85
636,1637,Student_637,19,Female,IT,Delhi,100,64
1337,2338,Student_1338,22,Female,ECE,Chandigarh,100,78
1450,2451,Student_1451,20,Male,CSE,Amritsar,100,66

In [29]:
df.sort_values(by='Marks', ascending=True).head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
22,1023,Student_23,23,Male,CE,Jaipur,35,98
1282,2283,Student_1283,19,Male,ME,Amritsar,35,75
1622,2623,Student_1623,21,Male,CE,Delhi,35,82
1021,2022,Student_1022,24,Male,CE,Chandigarh,35,84
1654,2655,Student_1655,21,Male,IT,Ludhiana,35,73
337,1338,Student_338,23,Female,CSE,Chandigarh,35,95
393,1394,Student_394,18,Female,ME,Delhi,35,94
946,1947,Student_947,25,Female,CE,Delhi,35,79
1814,2815,Student_1815,19,Male,ME,Ludhiana,35,87
753,1754,Student_754,23,Male,IT,Amritsar,35,65

In [30]:
df.sort_values(by='Marks', ascending=True).tail(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1554,2555,Student_1555,22,Male,ECE,Jaipur,100,98
449,1450,Student_450,19,Male,ECE,Chandigarh,100,84
1935,2936,Student_1936,24,Female,ME,Chandigarh,100,97
854,1855,Student_855,21,Female,CSE,Ludhiana,100,95
1600,2601,Student_1601,23,Female,ME,Delhi,100,87
1746,2747,Student_1747,22,Female,ME,Amritsar,100,85
1570,2571,Student_1571,24,Male,ME,Amritsar,100,94
1942,2943,Student_1943,22,Male,CSE,Chandigarh,100,70
270,1271,Student_271,21,Male,ECE,Ludhiana,100,85
308,1309,Student_309,23,Male,IT,Amritsar,100,89

In [31]:
df.rename(columns={'marks': 'students_marks'})

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [32]:
df.drop('City',axis=1)

      Student_ID          Name  Age  Gender Department  Marks  Attendance
0           1001     Student_1   19    Male        ECE     63          68
1           1002     Student_2   19    Male         CE     39          61
2           1003     Student_3   19    Male         IT     38          95
3           1004     Student_4   21  Female         IT     70          60
4           1005     Student_5   20  Female        ECE     54          73
...          ...           ...  ...     ...        ...    ...         ...
1995        2996  Student_1996   23  Female         CE     53          78
1996        2997  Student_1997   21  Female         CE     67          90
1997        2998  Student_1998   25    Male        ECE     56          93
1998        2999  Student_1999   25    Male        ECE     57          69
1999        3000  Student_2000   25    Male        CSE     59          72

[2000 rows x 7 columns]